class CitiesModel {
  static final List<String> suggestions = {
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'London',
    'Tokyo',
    'Colombo',
    'Kandy',
    'Galle',
    'Negombo',
    'Jaffna',
    'Anuradhapura',
    'Ratnapura',
    'Trincomalee',
    'Batticaloa',
    'Matara',
    'Kurunegala',
    'Badulla',
    'Nuwara Eliya',
    'Polonnaruwa',
    'Dambulla',
    'Hambantota',
    'Kalutara',
    'Puttalam',
    'Vavuniya',
    'Mannar',
    'Kilinochchi',
    'Monaragala',
    'Ampara',
    'Gampaha',
    'Matale',
    'Kegalle',
    'Mullaitivu',
    'Hatton',
    'Wattala',
    'Dehiwala',
    'Moratuwa',
    'Sri Jayawardenepura Kotte',
    'Panadura',
    'Beruwala',
    'Bentota',
    'Hikkaduwa',
    'Weligama',
    'Tangalle',
    'Mirissa',
    'Ella',
    'Sigiriya',
    'Pinnawala',
    'Kitulgala',
    'Haputale',
    'Arugam Bay',
    'Pasikudah',
    'Unawatuna',
    'Mount Lavinia',
    'Kataragama',
    'Dubai',
    'Mumbai',
    'San Francisco',
    'Seattle',
    'Boston',
    'San Diego',
    'Dallas',
    'Bandarawela',
    'Balangoda',
    'Balapitiya',
    'Battaramulla',
    'Boralesgamuwa',
    'Chilaw',
    'Embilipitiya',
    'Gampola',
    'Horana',
    'Ja-Ela',
    'Kadawatha',
    'Kalmunai',
    'Koggala',
    'Kuliyapitiya',
    'Minuwangoda',
    'Nawalapitiya',
    'Peliyagoda',
    'Piliyandala',
    'San Jose',
    'Austin',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Antonio',
    'Indianapolis',
    'Denver',
    'Washington',
    'El Paso',
    'Detroit',
    'Nashville',
    'Memphis',
    'Portland',
    'Oklahoma City',
    'Las Vegas',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Kansas City',
    'Mesa',
    'Atlanta',
    'Omaha',
    'Colorado Springs',
    'Raleigh',
    'Miami',
    'Long Beach',
    'Virginia Beach',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Arlington',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Tampa',
    'Bakersfield',
    'Aurora',
    'Honolulu',
    'Anaheim',
    'Santa Ana',
    'Corpus Christi',
    'Riverside',
    'Lexington',
    'St. Louis',
    'Stockton',
    'Pittsburgh',
    'Saint Paul',
    'Cincinnati',
    'Anchorage',
    'Greensboro',
    'Plano',
    'Newark',
    'Lincoln',
    'Toledo',
    'Orlando',
    'Chula Vista',
    'Irvine',
    'Fort Wayne',
    'Jersey City',
    'Durham',
    'St. Petersburg',
    'Laredo',
    'Buffalo',
    'Madison',
    'Lubbock',
    'Chandler',
    'Scottsdale',
    'Glendale',
    'Reno',
    'Norfolk',
    'Winston–Salem',
    'North Las Vegas',
    'Irving',
    'Chesapeake',
    'Gilbert',
    'Hialeah',
    'Garland',
    'Fremont',
    'Richmond',
    'Boise',
    'Baton Rouge',
    'Des Moines',
    'Spokane',
    'San Bernardino',
    'Modesto',
    'Fontana',
    'Santa Clarita',
    'Birmingham',
    'Oxnard',
    'Fayetteville',
    'Moreno Valley',
    'Rochester',
    'Huntington Beach',
    'Salt Lake City',
    'Grand Rapids',
    'Amarillo',
    'Yonkers',
    'Montgomery',
    'Akron',
    'Little Rock',
    'Huntsville',
    'Augusta',
    'Port St. Lucie',
    'Grand Prairie',
    'Tallahassee',
    'Overland Park',
    'Tempe',
    'McKinney',
    'Mobile',
    'Cape Coral',
    'Shreveport',
    'Frisco',
    'Knoxville',
    'Worcester',
    'Brownsville',
    'Vancouver',
    'Fort Lauderdale',
    'Sioux Falls',
    'Ontario',
    'Chattanooga',
    'Providence',
    'Newport News',
    'Rancho Cucamonga',
    'Santa Rosa',
    'Oceanside',
    'Salem',
    'Elk Grove',
    'Garden Grove',
    'Pembroke Pines',
    'Peoria',
    'Eugene',
    'Corona',
    'Cary',
    'Springfield',
    'Fort Collins',
    'Jackson',
    'Alexandria',
    'Hayward',
    'Lakewood',
    'Clarksville',
    'Palmdale',
    'Salinas',
    'Hollywood',
    'Pasadena',
    'Sunnyvale',
    'Macon',
    'Pomona',
    'Escondido',
    'Killeen',
    'Naperville',
    'Joliet',
    'Bellevue',
    'Rockford',
    'Savannah',
    'Paterson',
    'Torrance',
    'Bridgeport',
    'McAllen',
    'Mesquite',
    'Syracuse',
    'Midland',
    'Murfreesboro',
    'Miramar',
    'Dayton',
    'Fullerton',
    'Olathe',
    'Thornton',
    'Roseville',
    'Denton',
    'Waco',
    'Surprise',
    'Carrollton',
    'West Valley City',
    'Charleston',
    'Warren',
    'Hampton',
    'Visalia',
    'Coral Springs',
    'Columbia',
    'Cedar Rapids',
    'Sterling Heights',
    'New Haven',
    'Stamford',
    'Concord',
    'Kent',
    'Santa Clara',
    'Elizabeth',
    'Round Rock',
    'Thousand Oaks',
    'Lafayette',
    'Athens',
    'Topeka',
    'Simi Valley',
    'Fargo',
    'Norman',
    'Abilene',
    'Wilmington',
    'Hartford',
    'Victorville',
    'Pearland',
    'Vallejo',
    'Ann Arbor',
    'Berkeley',
    'Allentown',
    'Richardson',
    'Odessa',
    'Arvada',
    'Cambridge',
    'Sugar Land',
    'Beaumont',
    'Lansing',
    'Evansville',
    'Independence',
    'Fairfield',
    'Provo',
    'Clearwater',
    'College Station',
    'West Jordan',
    'Carlsbad',
    'El Monte',
    'Murrieta',
    'Temecula',
    'Palm Bay',
    'Costa Mesa',
    'Westminster',
    'North Charleston',
    'Miami Gardens',
    'Manchester',
    'High Point',
    'Downey',
    'Clovis',
    'Pompano Beach',
    'Pueblo',
    'Elgin',
    'Lowell',
    'Antioch',
    'West Palm Beach',
    'Everett',
    'Wichita Falls',
    'Gresham',
    'Billings',
    'Green Bay',
    'Daly City',
    'Burbank',
    'North Miami',
    'Broken Arrow',
    'Sandy Springs',
    'Boulder',
    'West Covina',
    'Norwalk',
    'Davenport',
    'Rialto',
    'Las Cruces',
    'San Mateo',
    'Lewisville',
    'South Bend',
    'Lakeland',
    'Erie',
    'Tyler',
    'Sandy',
    'Clinton',
    'Allen',
    'League City',
    'Longmont',
    'Edinburg',
    'Mission',
    'Bryan',
    'Baytown',
    'Pharr',
    'Missouri City',
    'Temple',
    'Flower Mound',
    'New Braunfels',
    'Cedar Park',
    'Georgetown',
    'San Marcos',
    'Rowlett',
    'Pflugerville',
    'Euless',
    'DeSoto',
    'Grapevine',
    'Bedford',
    'Cedar Hill',
    'Texas City',
    'Wylie',
    'Haltom City',
    'Keller',
    'Coppell',
    'Rockwall',
    'Duncanville',
    'Sherman',
    'The Colony',
    'Burleson',
    'Hurst',
    'Lancaster',
    'Friendswood',
    'Weslaco',
    'Del Rio',
    'Lufkin',
    'San Angelo',
    'Copperas Cove',
    'Schertz',
    'Kyle',
    'Leander',
    'Little Elm',
    'Waxahachie',
    'Cleburne',
    'Farmers Branch',
    'Southlake',
    'Weatherford',
    'Seguin',
    'Paris',
    'Corsicana',
    'Marshall',
    'Big Spring',
    'Harker Heights',
    'Alvin',
    'Angleton',
    'Bastrop',
    'Beeville',
    'Boerne',
    'Brenham',
    'Brownwood',
    'Canyon',
    'Carthage',
    'Crockett',
    'Cuero',
    'Dalhart',
    'Decatur',
    'Dumas',
    'Eagle Pass',
    'El Campo',
    'Fredericksburg',
    'Gainesville',
    'Gatesville',
    'Giddings',
    'Gonzales',
    'Graham',
    'Granbury',
    'Greenville',
    'Henderson',
    'Hereford',
    'Hillsboro',
    'Hondo',
    'Jacksonville',
    'Jasper',
    'Kerrville',
    'Kingsville',
    'La Grange',
    'Lampasas',
    'Levelland',
    'Liberty',
    'Livingston',
    'Lockhart',
    'Madisonville',
    'Marble Falls',
    'Marlin',
    'Mason',
    'Matador',
    'Menard',
    'Mineral Wells',
    'Mount Pleasant',
    'Nacogdoches',
    'Orange',
    'Palestine',
    'Pampa',
    'Pecos',
    'Plainview',
    'Port Arthur',
    'Port Lavaca',
    'Quanah',
    'Raymondville',
    'Refugio',
    'Rocksprings',
    'San Benito',
    'Snyder',
    'Sonora',
    'Stephenville',
    'Sweetwater',
    'Taylor',
    'Texarkana',
    'Uvalde',
    'Vernon',
    'Victoria',
    'Yoakum',
    'Yorktown',
    'Zapata'
  }.toList();
}
